### ISSUE TITLE
[Bug] Failed to delete list item in Tab Lists

### ISSUE THREAD

**Issue by beenotung** [cnwangjie/better-onetab#182]
扩展版本 (extension version):
1.4.5

浏览器版本 (browser version):
Firefox Quantum 64.0.2 (64-bit)

操作系统 (operating system):
Windows 10

问题描述 (problem description):
Failed to delete list item

实际行为 (actual behavior):
1. The checked items are not removed.
2. The drop-down menu is not auto closed as well.

期望行为 (expected behavior):
1. The checked items should be removed from the tab list.
2. The the drop-down menu should be closed after clicking the menu item.

重现步骤 (reproduce step):
1. open the windows with a few tabs
2. use the extension to zip all tabs in current window
3. from the tab list, check some tabs (tick a few items)
4. click the option drop-down menu (three dots in icon)
5. click "Remove" in the last item in drop-down menu

**Comment by cnwangjie** [comment]
Hi! Thank you for your report. Recently received a lot of reports about data modifications not being applied. I will try to solve it.

**Comment by rpnfan** [comment]
I confirm the same problem. Not data modificiations are carried out at all. The popup-menu would allow to delete or move to other lists and so on. None of the functions work. The popup-menu does not react on any mouse-click to do any of the named actions.

**Comment by Pictor13** [comment]
Same here.
Here are the details about my issue.

----

扩展版本 (extension version): 1.4.5
浏览器版本 (browser version): 75.0.3770.142 (Official Build) (64-bit)
操作系统 (operating system): macOS Mojave
问题描述 (problem description): looks like the events (for triggering changes) are not handled properly.

实际行为 (actual behavior):
* when selecting some items from the list (via the checkboxes) and then trying to perform an action on them (e.g. "Remove", or "Duplicate", or "Open"), nothing happens.
Even refreshing the page shows that the command has not been sent or performed any change.
Also, sometimes after some clicks, the three-dots menu doesn't appear anymore (have to refresh the whole extension page).

期望行为 (expected behavior):
* when selecting some items from the list (via the checkboxes) and then trying to "Remove" them, they should disappear from the list.

重现步骤 (reproduce step):
* choose a list, select some tabs (via the checkboxes)
* click the three-dots menu button
* click on "Remove" to try removing the selected items.

**Comment by Pictor13** [comment]
Looks an issue just on Vuejs side. Probably the events are not emited correctly (didn't look at the code yet).
All the operation performed via the right-click on the BetterOnetab icon in the extensions bar (e.g. "store into a titled list") work correctly.
Is not working *just* in the Vuejs UI.

**Comment by cnwangjie** [comment]
Thank you for your report. I've published a new version. Please reference [https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965](https://github.com/cnwangjie/better-onetab/issues/121#issuecomment-519410965)

If your problem still exists or there is no relation to this problem, please submit a new issue or reopen this issue.

**Comment by DuncanCragg** [comment]
I'm still seeing this on v1.4.7 in Chrome; the three-dot menu actions next to the checkbox column are all dead.

**Comment by DuncanCragg** [comment]
I see you're getting `sentry.io` notifications for this, so you can see if it's just me or everyone! :-D
