### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by rayman89** [cnwangjie/better-onetab#33]
I noticed that the page context menu does not work depending on where you right click. For example on github if you right click on a text box like the one I'm typing now the context menu for better onetab does not appear. I think you should make it so that it appears on every page and on every element of a page.

Also could you consider adding a tab context menu for better one tab (a menu that appears when you right click on a tab)?

**Comment by cnwangjie** [comment]
Yes, it only displays when you right click on page and icon. [Here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType) shows the possible place the context menus can be displayed. I just set `browser_action` & `page` because of the compatibility and avoid unexpected situation.

**Comment by rayman89** [comment]
could you consider adding as an option a tab context menu (a menu that appears when you right click on a tab)?
