### ISSUE TITLE
Support storing into a specific list

### ISSUE THREAD

**Issue by Pictor13** [cnwangjie/better-onetab#40]
I am happy to see somebody already started the work I wanted to do 😊
(create an opensource **OneTab**, with additional features; because **OneTab** is not updated since a year and there is no way to contact the author or to contribute to the project).

But **better-onetab** lacks an important feature: being able to send the tabs to a specific list, by name, or (less important) to a new named list.

E.g. having a list *"funny articles"* with some entries, I would like to quickly add a link/tab to it, like:

1. click the extension icon to show the simple list popup
2. click a *store-in-this-list* icon (by default stores selected-tabs; alternatively allows to store all-tabs-in-window, tabs-to-right, tabs-to-left)

rather than:

1. storing the selected tab
2. go into **better-onetab** tab
3. drag'n'drop the new tab into my *"funny articles"* list
4. close **better-onetab** tab

Ideally the simple-list would allow the most useful operations over existing lists, and allow to create a list with a specific name.

Let me know if it makes sense to you, if you want to add it in the roadmap, and if I can eventually help with implementing this (I see you use VUE, and I was actually interested in learning it; so could be a good opportunity 😉).

**Comment by cnwangjie** [comment]
Hi,

This was in my roadmap for a long time (I wrote it on the projects page as Chinese :joy: ). Because I usually make the feature mentioned by users or fix bugs first, I lay it aside to now. It is very nice if you are willing to implement it.

There are two ways in my idea.

 - Add it in the context menu similar with the way to implement of onetab.
 - Add a button on every item in the simple list.

I am not sure which way is better and easy to implement, but I hope both of them could be implemented finally.

Both of them need to make some changes to the `storeTabs` method in `src/common/tabs.js` first to allow store tabs to a specific list.

For the first plan, it should make changes in `setupContextMenus` method in `src/background.js` and call it in the handler of storage changed event. The second need to make some changes to `src/page/Popup.vue`. 

If you have any other ideas It is welcome to share them.

Thank you.

**Comment by cnwangjie** [comment]
I've added this feature in v1.3.10. It is welcome to submit a new issue if there are any problems.
