### ISSUE TITLE
New Logo and Banner for BetterOneTab

### ISSUE THREAD

**Issue by Yasujizr** [cnwangjie/better-onetab#5]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an new icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a icon.

Best Regards

**Comment by cnwangjie** [comment]
@Yasujizr Hi, sorry for the late reply. This extension is a personal open source project. Now the logo is a free icon I found on the web and the banner was I doing it casually. If you can design a logo or banner for this project specifically, I am very happy to use it. But this is a non-commercial project, so I can't pay anything for it. And thank you very much.

**Comment by Yasujizr** [comment]
No need to pay. It would be nice for me to just pass my name on the project. The portfolio expands and gives me the opportunity to make a beautiful presentation. Do you have a template for your logo that you have in mind? Could you give me a brief about the project?

**Comment by cnwangjie** [comment]
@Yasujizr  Ok, I don't know if you used to be a user of onetab or have you used better-onetab, If not then you can try to install it. It can help you temporarily storing tabs when there are too many tabs on your window, and manage and group a large number of tabs. 

Currently, better-onetab uses the same funnel icon as the onetab. I think this means filtering, it is also necessary to provide both list and management functions. Compared with onetab, better-onetab uses a flat and more modern design icon, and the UI is the same. 

![image](https://user-images.githubusercontent.com/7459652/43358961-c983182e-92cc-11e8-87f5-9c11de219363.png) the icon of onetab     ![image](https://user-images.githubusercontent.com/7459652/43358962-ce85ca10-92cc-11e8-8a4c-e8be9206f5c1.png) the icon of better-onetab currently

And the banner as you see, it is very simple and with a pink background. It just because I personally prefer the two colors cyan and pink. I hope to keep the simple and flat design, but with more refined fonts. This is just my personal favor. However, it is necessary to keep the background color is a single color and the body is centrally, this makes it easy to adapt to different sizes of banners.

https://chrome.google.com/webstore/detail/better-onetab/eookhngofldnbnidjlbkeecljkfpmfpg

![920x680](https://user-images.githubusercontent.com/7459652/43359034-5f930cce-92ce-11e8-84ec-11eed968d121.png)

![640x400](https://user-images.githubusercontent.com/7459652/43359035-62038efc-92ce-11e8-8436-9200705adf10.png)

I hope this can help you, I am happy to see what you design.

**Comment by Yasujizr** [comment]
![betteronetab](https://user-images.githubusercontent.com/36993664/43740127-07f95ef8-99d3-11e8-8221-716d103cb34b.jpg)

Simplified version of the funnel. At the same time, it reflects the intent of the program. Increasingly smaller units represent storage and filtering. If u want, units to be used in the logo will be reduced by region. Sorry for late reply.

*After the logo selection, we can start designing the poster.

**Comment by cnwangjie** [comment]
@Yasujizr Thanks for your great work. I really like the first one. It gives me a modern feel. I think it would be great to use it.

By the way, the image that will be used as the icon of extension should without margins around them.

**Comment by Yasujizr** [comment]
Hi, I do not quite understand. Which one did you choose? Like the 2nd when there are no edges?
![untitled-1](https://user-images.githubusercontent.com/36993664/44276939-c242ab80-a251-11e8-919b-f530acf53d15.jpg)

**Comment by cnwangjie** [comment]
@Yasujizr Hi, Both of them are ok. I think currently is good enough in poster. But there should not is extra space around the image content if we use it as an icon.

It should like ![image](https://user-images.githubusercontent.com/7459652/44514985-04f20100-a6f4-11e8-9223-00fec58f9929.png) instead of ![image](https://user-images.githubusercontent.com/7459652/44515019-13d8b380-a6f4-11e8-95d7-80ef3b5b4289.png)

Hope this can explain my meaning. :joy_cat:

**Comment by Yasujizr** [comment]
Hi, I have added svg and png files. I can make PR for you if you like. You can contact me when you have another graphic job. I will update the link when the logotype is finished.

https://drive.google.com/open?id=1dpd8Q600VqcaFRfQ8HHuZy901_IoJERF

**Comment by cnwangjie** [comment]
@Yasujizr Great. I think they are near done except a few works to resize the images to usable sizes.

The icons need three different sizes: 16x16, 48x48, 128x128 (png with transparent background). And We need some banner with the new icon. The banners sizes are 1280x800, 440x280, 920x680, 1400x560 (png without alpha). I think I can wait for you to complete the new banner and it is nice that we can publish a new version with a new icon and new features. It will be a good chance to show your great work.

And I noticed that there are a different number of the line in different size images. Maybe we should stay the same number, such as leave three line in each size? Or you can work with your idea if you have a better way to handle it.

Thank you

**Comment by cnwangjie** [comment]
@Yasujizr Hi, I really like the new banner you made. I am very willing to show it to everyone. Could you help me generate it into the required size and format like my comment above? I guess you should be using a professional design software and that should be easy for you. But there is no software on my computer that can handle pictures easily.

**Comment by Yasujizr** [comment]
I increased the banner size and updated it to jpeg. You can write me in any design question. 

Thank u, :)

https://drive.google.com/open?id=1dpd8Q600VqcaFRfQ8HHuZy901_IoJERF

**Comment by cnwangjie** [comment]
@Yasujizr Thank you, but could you make the icons to square, separately 16x16, 48x48, 128x128 and make four different size banners, separately 1280x800, 440x280, 920x680, 1400x560? That is all we need. :joy:

**Comment by Yasujizr** [comment]
If I make the icons 16x16, they will be corrupted. So we have to do it as 16x13 48x39 128x103. Otherwise it will look like it was pulled from the tops. I added the size of the logo on top. I'm setting up the banners now.

**Comment by cnwangjie** [comment]
@Yasujizr I think you do not need to stretch the picture, can you put the current icon content to center and leave blank on the side? And the size is the requirement of the chrome extension store.

**Comment by Yasujizr** [comment]
I think I managed it this time. :D I have updated the link. I erased old files. I installed the new ones. I arranged the banners by size. I arranged the logo as you said. 

https://drive.google.com/open?id=1dpd8Q600VqcaFRfQ8HHuZy901_IoJERF

**Comment by cnwangjie** [comment]
@Yasujizr Hi, I've changed to use new icon and add thanks message in the readme. It is nearly ready to publish a new version, but a found the size of banners still not correct. The unit of sizes we need is the pixel. If we try to upload a different size we will get an error. Can you make a change to the banner again? Make sure they are the correct size. And it seems that the current picture has white edges, hope you can solve this. Thank you.

![image](https://user-images.githubusercontent.com/7459652/44866022-91815e00-acb6-11e8-864e-c42a48d8a237.png)

**Comment by Yasujizr** [comment]
Hi, I've updated the banners. The whiteness was removed and the dimensions adjusted. Probably the right size at the moment. Thank you for the read.me. I think Logotype looks better in Read.me. I uploaded it with new colors. It's your decision, though. :)

![forread me](https://user-images.githubusercontent.com/36993664/44917039-f208ad80-ad3f-11e8-85e9-e29489f0ffb4.png)

**Comment by cnwangjie** [comment]
@Yasujizr Nice work! I've changed all image to your design and published a new version.
