### ISSUE TITLE
Settings menu item does not vertically scale to content

### ISSUE THREAD

**Issue by scott-joe** [cnwangjie/better-onetab#84]
## General Information
**扩展版本 (extension version):** Version: 1.3.11
**浏览器版本 (browser version):** 71.0.3578.98 (Official Build) (64-bit)
**操作系统 (operating system):** macOS 10.14.2 (18C54)

## Issue Information
**问题描述 (problem description):**  Settings item list does not handle vertical content when content is more than expected height.
**实际行为 (actual behavior):**
<img width="410" alt="screen shot 2018-12-24 at 10 50 01" src="https://user-images.githubusercontent.com/2026866/50403093-dbacb480-0769-11e9-9171-bbcf27520e18.png">
**期望行为 (expected behavior):**  List item should style height to handle multi-line content.
**重现步骤 (reproduce step):** Go to Settings page

**Comment by cnwangjie** [comment]
Hi, thank you for your report. It is caused by the horizontal resolution is too low to display the whole content. I tested that when the resolution is less than 1900px, it will cause the content to break to three lines. I'll try to decrease the content and display complete information as a popup tooltip.
