### ISSUE TITLE
Cannot locate to tab if tab is folded

### ISSUE THREAD

**Issue by rsun-thoughtworks** [cnwangjie/better-onetab#85]
As a user, I fold all tabs and then search keyword in the search box.
I clicked the item listed below the search box, I expect the folder contains the item will unfold automatically.

**Comment by rsun-thoughtworks** [comment]
hello anyone?

**Comment by cnwangjie** [comment]
Hi, in my tests the list will be expand if an item in the search result be clicked. Could you provide a detail reproduce steps? And I'll try to check it again. Thank you.

**Comment by rsun-thoughtworks** [comment]
Version: 1.3.11
Source: Chrome Web Store
======================
I have this condition:

tabgroup1
  - url1
  - url2
tabgroup2
  - url3
  - url4

given the condition that I have folded all tabgroups.
if I search url4 and click the displayed match below search box as I typed.
I should be able to see tabgroup2 unfold itself and reveal url4.

Thanks!

**Comment by cnwangjie** [comment]
Hi, thank you very much for your report. I found it does not work when the first item of a list be clicked because of a wrong judgment condition. (https://github.com/cnwangjie/better-onetab/commit/98f9a0b8507bf8cb500d0cc2fc6fb13cd17254cf#diff-e6038c5b61fd643e265178d7fbde762aL239)

I'll publish a new version with this fix. And according to your suggestion, I rebase the all new commits to the develop branch and keep the master branch is the same with the release version.

Thank you again.
